templates/views/index.pug
this fixes  https://github.com/zerobase-io/smart-tracing/issues/4
=> fixed slack links

Dockerfile, docker-compose.yaml
This is a multi-stage docker file that can be later on improved and adjusted for production purposes, to get a lean Image.
`docker-compose up
`
Rebuild image:
`docker-compose up -d --no-deps --build --remove-orphans ts-prod`
=> Ads initial docker and docker compose file

.github/workflows/dockerfile_pull_request_verifier.yml, .github/workflows/dockerfile_release.yml, Dockerfile
Add 2 workflow jobs:
1) Build Dockerfile
This job will run on a pull request that changed the Dockerfile to make sure that it can still be built.
2) Build container and push to Dockerhub
This job will run on merge or push directly to master and it will build and push the container to Dockerhub
=> Add workflow jobs for Docker

public/overrides.css, src/controller.ts, src/templates/modal/scan-status.pug, src/templates/navigation/archive/primary.pug, src/templates/navigation/primary.pug, src/templates/pages/businesses.pug, src/templates/pages/healthcare.pug, src/templates/pages/home.pug, src/templates/pages/individuals.pug, src/templates/views/index.pug
Resolves:
Bug (https://github.com/zerobase-io/zerobase_app/issues/7)
Bug (https://github.com/zerobase-io/zerobase_app/issues/2)
Bug (https://github.com/zerobase-io/zerobase_app/issues/5)
Bug (https://github.com/zerobase-io/zerobase_app/issues/3)
Content Updates (https://github.com/zerobase-io/smart-tracing/issues/48)
Establishes: 
Content Update (https://github.com/zerobase-io/smart-tracing/issues/68)
=> frontend cleanup

.github/workflows/deploy-to-s3.yml
adding runtime_api_host variable under deploy-to-s3 env configuration
=> aws deploy fix

src/templates/pages/contact.pug, src/templates/pages/feedback.pug
Uses airtable "autosize height" script to make sure the form is full height on all viewports. Resolves #166, #164
=> airtable height

src/templates/navigation/footer.pug, src/templates/navigation/secondary.pug, src/templates/pages/about_us.pug, src/templates/pages/business_landing.pug, src/templates/pages/community.pug, src/templates/pages/home.pug, src/templates/pages/individuals_landing.pug, src/templates/views/index.pug
stylistic changes from privacy-first to privacy first and then changing tag line
resolves #190, resolves #162
=> Privacy-first to Privacy First && Tag line to "Privacy First Contact Tracing for Communities"

src/router.ts, src/templates/modal/register.pug, src/templates/pages/individuals_landing.pug
=> registration only occurs on first scan

src/templates/modal/feedback.pug, src/templates/modal/register-notifications.pug, src/templates/modal/scan-status.pug, src/templates/pages/contact.pug
Fix for Contact Page overwrite
Introduces new modals for opt-in mobile notifications and feedback
=> fixes contact, intros new modal

src/templates/navigation/footer.pug, src/templates/navigation/secondary.pug, src/templates/pages/about_us.pug, src/templates/pages/business_landing.pug, src/templates/pages/community.pug, src/templates/pages/home.pug, src/templates/pages/individuals_landing.pug
changes all privacy first to privacy-first and content changes on the about_us page from camille 
closes #213 closes #211 closes #210 closes #212 closes #214 closes #216
=> Aly.about page

src/templates/navigation/footer.pug
Adds a version tag to footer, gives some sanity when looking at staging.zerobase.io and making sure that version is the most updated one.
=> add version tag

src/controller.ts
Reverts zerobase-io/smart-tracing#235
=> Revert "remove semicolon, but this doesnt cause errors"

src/templates/navigation/footer.pug
Reverts zerobase-io/smart-tracing#233
=> Revert "add version tag"

src/controller.ts, src/router.ts, src/scanner.ts
Reverts zerobase-io/smart-tracing#231
=> Revert "undefined deviceID, updates API to handle null states"

src/templates/modal/feedback.pug, src/templates/modal/register-notifications.pug, src/templates/pages/business_register.pug, src/templates/pages/healthcare_register.pug
=> John.signup more links

src/templates/navigation/footer.pug
=> Footer Edits

src/templates/pages/home.pug
=> Small privacy tag line change in home page 

src/templates/navigation/footer.pug, src/templates/pages/volunteer_landing.pug
=> removed some extraneous styles, fixed join us button

buildUtils.js, devServer.js, src/controller.js
Builds off `tom.javascript_router` so I set that as the target branch. However, we can merge directly to master if `tom.javascript_router` is already there.
Let me know if you have any questions!
=> Convert src/controller.ts to javascript

src/router.js, src/templates/navigation/secondary.pug
Resolves #268 for @twoangstroms  and loop11 user testing.
Only available for staging.zerobase.io/test, clicking scan will trigger a success
=> /test route for loop11

src/controller.js
Resolves a scanning error where the deviceID is incorrect on the API path
=> resolves scan bug, introduced in refactor

src/router.js, src/templates/pages/home.pug, src/templates/toast/scanner-error.pug, src/templates/views/index.pug
Need to test chrome mobile video permissions. Will alert if for some reason permissions are default set to false or if navigator.getUserMedia does not exist
Updates test QR for /test
Also resolves issue of x button on internal scanning screen not working if permission is not granted or if getUserMedia is not valid since it was initialized within the getUserMedia function as opposed to outside of its scope
=> alert for scanner permissions

src/templates/modal/register-notifications.pug, src/templates/pages/about_us.pug, src/templates/pages/privacy_landing.pug
=> Updated content as part of Issue #279

src/router.js, src/templates/pages/terms.pug
=> Added content to terms page, added terms page to router

.eslintrc.json, .gitignore, README.md, babel.config.js, jest-custom-environment.js, jest-puppeteer.config.js, jest-puppeteer.mobile.config.js, jest.config.js, package-lock.json, package.json, tests/__pages__/HomePage.js, tests/__pages__/RegisterBusinessPage.js, tests/__pages__/RegisterHealthcarePage.js, tests/config/setup.js, tests/config/teardown.js, tests/specs/desktop/business.spec.js, tests/specs/desktop/healthcare.spec.js, tests/specs/desktop/scan.spec.js, tests/specs/desktop/smoke-desktop.spec.js, tests/specs/mobile/scan.spec.js, tests/specs/mobile/smoke-mobile.spec.js, tests/utils/fullPageScreenshot.js
Using Jest and Puppeteer for automation of the main user flows. Includes the initial integration with Applitools to take screenshots of every route except for `/scan` in Desktop and emulated mobile mode.
=> Add the initial UI automation suite

src/components/pages/IndividualsLanding.js
=> [#308]: Migrate `individuals_landing.pug` to a React component.

src/components/pages/Home.js
Resolves #307 
Couldn't debug why the styling is broken on the home page, would appreciate any help debug this issue cc @JohnCLo
=> [#307]: Migrate `home.pug` to a React component.

src/components/pages/BusinessLanding.js
=> [#303]: Refactored business-landing to react

src/components/pages/Contact.js
=> [#305]: Refactored contact us to pure react component.

src/components/components/Form/SurveyComponents/SurveyQuestions.js, src/components/pages/SelfReporting/SelfReportingPages.js, src/components/pages/SelfReporting/SurveySteps.js
=> [334]: Add symptom report question step 6 (just the form).

src/components/components/Form/PhoneNumberField.js, src/components/pages/BusinessRegister.js, src/templates/pages/contact.pug
=> fix phone number format and form issues

package-lock.json, src/components/pages/VolunteerLanding.js
VolunteerLanding.js:
Changed volunteer registration link to airtable versus google doc.
Resolves Pull Request #340
=> Update volunteer links in response to PR #340

src/components/pages/VolunteerLanding.js
Changes airtable form link for Volunteer registration to Google form link.
Fixes Issues #346 and deprecates Issue #340 
@ekraay, @cagarwa, @eriksogn
=> Changed Goolge link for volunteer registration

src/templates/navigation/footer.pug, src/templates/navigation/secondary.pug
These requires for the image paths should update the logo properly along with the files from PR #348 . 
If the images wind up not loading, please push these changes into master.
=> Add img path requires for webpack
